name: Build Docker Images
on:
  workflow_dispatch: 
  push:
    branches:
      - main
jobs:
  publish:
    name: Publish Docker Container
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push web
        uses: docker/build-push-action@v3
        with:
          context: .
          file: small-docker/Dockerfile
          tags: ghcr.io/bryonlewis/dive-dsa-slicer/dive-dsa-slicer:latest
          push: true
